"""Evidence-bound domain contracts for white-box quality-risk discovery."""

from aiverify.discovery.models import (
    ChangeTarget,
    ContextEdge,
    ContextFact,
    ContextNode,
    ContextPath,
    DiscoveryContractError,
    DiscoveryTarget,
    ProvenanceRef,
    ProjectTarget,
    QualityContextGraph,
    target_from_dict,
)
from aiverify.discovery.context import (
    ContextCollectionResult,
    collect_context,
    load_context_manifest,
    trace_backward,
    trace_forward,
)
from aiverify.discovery.contracts import (
    AdmissionResult,
    AttackOperator,
    AttackPlan,
    ContractDrift,
    DiscoveryCampaign,
    FailureChain,
    Finding,
    ProjectRiskMap,
    QualityContract,
    ResidualRisk,
    RiskHypothesis,
    RiskPrior,
    admit_attack_plan,
    admit_experiment,
)
from aiverify.discovery.schema import (
    load_schema,
    self_validate_schema,
    validate_contract,
    validate_discovery_document,
)

__all__ = [
    "ChangeTarget",
    "ContextCollectionResult",
    "ContextEdge",
    "AdmissionResult",
    "AttackOperator",
    "AttackPlan",
    "ContextFact",
    "ContextNode",
    "ContextPath",
    "ContractDrift",
    "DiscoveryContractError",
    "DiscoveryCampaign",
    "DiscoveryTarget",
    "FailureChain",
    "Finding",
    "ProjectRiskMap",
    "ProvenanceRef",
    "ProjectTarget",
    "QualityContract",
    "QualityContextGraph",
    "ResidualRisk",
    "RiskHypothesis",
    "RiskPrior",
    "admit_attack_plan",
    "admit_experiment",
    "collect_context",
    "load_context_manifest",
    "load_schema",
    "self_validate_schema",
    "target_from_dict",
    "trace_backward",
    "trace_forward",
    "validate_contract",
    "validate_discovery_document",
]
