"""Runner primitives for Smoke Slice and M1 verification runs."""

from aiverify.runner.admission import (
    AdmissionResult,
    CleanCheckoutSourceAuthority,
    HostAuthority,
    HostWorktreeIdentity,
    PlannedRunnerOptions,
    ProductionSeamAdmissionError,
    SourceAuthority,
    SourceAuthorityBinding,
    admit_production_seam,
    establish_and_abandon_temporary_record,
    verify_admitted_receipt,
    write_admission_receipt,
)
from aiverify.runner.codex_backend import (
    CodexCliBackend,
    CodexCliError,
    JourneyExecutionRequest,
)
from aiverify.runner.command import CommandResult, CommandRunner, SubprocessCommandRunner
from aiverify.runner.deterministic_backend import (
    AndroidLayoutDeviceAdapter,
    DeterministicAndroidBackend,
    DeterministicDriverError,
    DeterministicDriverPlan,
    DeterministicDriverPlanError,
    DeterministicDriverRequest,
    DeterministicPlanAction,
    LayoutObservation,
    RecordingEvidenceSink,
    load_deterministic_driver_plan,
    validate_deterministic_driver_plan,
)
from aiverify.runner.evidence import AndroidEvidenceCollector, EvidenceCheckpoint
from aiverify.runner.journey import (
    JourneySegment,
    JourneySegmentFlow,
    JourneySegmentRunner,
    scenario_to_segments,
    segment_to_journey_xml,
)
from aiverify.runner.journey_backend import (
    CODEX_CLI,
    DEFAULT_JOURNEY_BACKEND,
    DETERMINISTIC_ANDROID_V1,
    DriverPlanBinding,
    JourneyBackend,
    JourneyBackendSelectionError,
    JourneyBackendUnavailableError,
    JourneyDriverSelection,
    JourneyExecutionResult,
    SUPPORTED_JOURNEY_BACKENDS,
    backend_id,
    create_journey_backend,
)
from aiverify.runner.run_spec import (
    AssertionSpec,
    DryRunPlan,
    HostProjectLocator,
    RunSpec,
    RunSpecError,
    ScenarioSpec,
    SystemEventSpec,
    load_run_spec,
)
from aiverify.runner.system_events import (
    DeviceSystemEventInjector,
    SystemEventInjectionError,
)
from aiverify.runner.verdict import judge_l2_from_android_layout

__all__ = [
    "AdmissionResult",
    "AndroidEvidenceCollector",
    "AssertionSpec",
    "CodexCliBackend",
    "CodexCliError",
    "CODEX_CLI",
    "CommandResult",
    "CommandRunner",
    "AndroidLayoutDeviceAdapter",
    "CleanCheckoutSourceAuthority",
    "DryRunPlan",
    "DeviceSystemEventInjector",
    "DETERMINISTIC_ANDROID_V1",
    "DeterministicAndroidBackend",
    "DeterministicDriverError",
    "DeterministicDriverPlan",
    "DeterministicDriverPlanError",
    "DeterministicDriverRequest",
    "DeterministicPlanAction",
    "DEFAULT_JOURNEY_BACKEND",
    "DriverPlanBinding",
    "EvidenceCheckpoint",
    "HostProjectLocator",
    "HostAuthority",
    "HostWorktreeIdentity",
    "JourneyExecutionRequest",
    "JourneyExecutionResult",
    "LayoutObservation",
    "JourneySegment",
    "JourneySegmentFlow",
    "JourneySegmentRunner",
    "JourneyBackend",
    "JourneyBackendSelectionError",
    "JourneyBackendUnavailableError",
    "JourneyDriverSelection",
    "PlannedRunnerOptions",
    "ProductionSeamAdmissionError",
    "SourceAuthority",
    "SourceAuthorityBinding",
    "RunSpec",
    "RunSpecError",
    "RecordingEvidenceSink",
    "ScenarioSpec",
    "SubprocessCommandRunner",
    "SystemEventSpec",
    "SystemEventInjectionError",
    "SUPPORTED_JOURNEY_BACKENDS",
    "backend_id",
    "judge_l2_from_android_layout",
    "load_run_spec",
    "load_deterministic_driver_plan",
    "validate_deterministic_driver_plan",
    "admit_production_seam",
    "establish_and_abandon_temporary_record",
    "scenario_to_segments",
    "segment_to_journey_xml",
    "verify_admitted_receipt",
    "write_admission_receipt",
    "create_journey_backend",
]
