"""Contract tests for the M9 freeze hand-off."""

from __future__ import annotations

import copy
import json
from pathlib import Path

import pytest

from aiverify.bench.m9_qualification import (
    LANE_IDS,
    M9QualificationError,
    SOURCE_ORIGIN,
    audit_contradiction_packet,
    audit_neutral_packets,
    load_manifest,
    validate_admission_receipts,
)


ROOT = Path(__file__).parents[2]
MANIFEST = ROOT / "bench/m9/m9-project-qualification-v1.json"


def test_frozen_manifest_is_not_available_before_materialization() -> None:
    """The generator creates the manifest; a source checkout may be pre-freeze."""

    if not MANIFEST.exists():
        pytest.skip("#136 manifest is generated by the freeze evidence script")
    manifest = load_manifest(MANIFEST)
    assert manifest.qualification_id == "m9-project-qualification-v1"
    assert tuple(item["lane_id"] for item in manifest.lanes) == LANE_IDS


def test_neutral_packets_reject_ground_truth_terms() -> None:
    packets = [
        {
            "packet_id": "packet-01",
            "lane_id": "m9-lane-01",
            "run_spec_sha256": "a" * 64,
            "scenario_id": "m9-lane-01",
        }
    ]
    audit = audit_neutral_packets(packets)
    assert audit["status"] == "pass"
    assert audit["mapping_released"] is False

    leaked = copy.deepcopy(packets[0])
    leaked["result"] = "locally_supported"
    assert audit_neutral_packets([leaked])["status"] == "fail"


def test_contradiction_packet_is_excluded_before_side_effects() -> None:
    audit = audit_contradiction_packet(
        {
            "packet_id": "m9-136-incomplete-context-v1",
            "required_fields": ["target_source_identity", "context_graph", "operator_registry"],
            "present_fields": ["packet_id"],
            "expected_admission": "rejected",
            "formal_denominator": False,
            "side_effects": False,
            "rejection_boundary": "before_any_build_device_agent_or_runtime_side_effect",
        },
        observed_command_calls=[],
    )
    assert audit["status"] == "pass"
    assert audit["pre_side_effect_rejection"] is True
    assert audit["command_calls"] == []


def test_admission_receipt_validator_requires_six_clean_receipts() -> None:
    def receipt(lane_id: str, digest: str, commit: str) -> dict[str, object]:
        return {
            "status": "admitted",
            "admitted": True,
            "run_spec": {
                "path": f"/repo/bench/m9/run-specs/{lane_id}.yaml",
                "sha256": digest,
                "scenario": lane_id,
            },
            "host": {"origin": SOURCE_ORIGIN, "commit": commit},
            "runner_policy": {
                "options": {
                    "device": "emulator-5554",
                    "backend": "codex_cli",
                    "requested_driver_model": "codex-default",
                    "requested_l3_model": "codex-default",
                    "runner_policy_version": "m9-production-seam-v1",
                    "expected_source_commit": commit,
                }
            },
            "side_effects": {
                "external": False,
                "build": False,
                "device": False,
                "agent": False,
            },
        }

    expected = {
        lane_id: {"run_spec_sha256": f"{index:064x}", "commit": "a" * 40}
        for index, lane_id in enumerate(LANE_IDS, start=1)
    }
    receipts = [
        receipt(lane_id, expected[lane_id]["run_spec_sha256"], "a" * 40)
        for lane_id in LANE_IDS
    ]
    assert (
        validate_admission_receipts(receipts, expected_run_specs=expected)["status"]
        == "pass"
    )
    assert (
        validate_admission_receipts(
            [receipts[0]] * 6, expected_run_specs=expected
        )["status"]
        == "fail"
    )


def test_manifest_rejects_role_leakage_when_present(tmp_path: Path) -> None:
    if not MANIFEST.exists():
        pytest.skip("#136 manifest is generated by the freeze evidence script")
    document = json.loads(MANIFEST.read_text(encoding="utf-8"))
    document["lanes"][0]["role"] = "defect"
    tampered = tmp_path / "tampered.json"
    tampered.write_text(json.dumps(document), encoding="utf-8")
    with pytest.raises(M9QualificationError, match="role/variant"):
        load_manifest(tampered)
